package com.daman.admin.service;

import com.daman.admin.entity.AppSetting;
import com.daman.admin.entity.License;
import com.daman.admin.repository.AppSettingRepository;
import com.daman.admin.repository.ClientConfigRepository;
import com.daman.admin.repository.LicenseRepository;
import lombok.RequiredArgsConstructor;
import lombok.extern.slf4j.Slf4j;
import org.springframework.beans.factory.annotation.Value;
import org.springframework.stereotype.Service;
import tools.jackson.databind.JsonNode;
import tools.jackson.databind.json.JsonMapper;

import java.io.IOException;
import java.io.UncheckedIOException;
import java.net.URI;
import java.net.http.HttpClient;
import java.net.http.HttpRequest;
import java.net.http.HttpResponse;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.nio.file.StandardCopyOption;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.time.Duration;
import java.time.LocalDateTime;
import java.util.ArrayList;
import java.util.List;
import java.util.Optional;
import java.util.Properties;

/**
 * "Run the dev checkout as client X" — writes {@code client.config.json} /
 * {@code client-meta.properties} into the workspace (either the real per-client
 * config or the neutral generic one), drops {@code ~/.daman/runtime.properties},
 * and — in the machine-id / dev-licence / db-copy half added later — mints a dev
 * v2 licence and points the checkout at a database the owner chooses. {@link #devReset()}
 * puts the checkout back to the neutral generic config.
 *
 * SECURITY: every method here writes to the local filesystem and (in the licence
 * half) mints licences without the usual machine-ID friction. This is acceptable
 * ONLY because the admin backend is a locally-run developer tool. It must never be
 * reachable from a network-exposed admin backend — revisit before the
 * admin-Cloudflare-deploy work.
 */
@Service
@RequiredArgsConstructor
@Slf4j
public class DevRunService {

    // Injected for the dev-licence / machine-id / db-copy half of this service.
    private final ClientConfigService clientConfigService;
    private final LicenseKeyService licenseKeyService;
    private final LicenseRepository licenseRepository;
    private final ClientConfigRepository clientConfigRepository;
    private final AppSettingRepository appSettingRepository;

    @Value("${daman.workspace:D:/Daman/src}")
    private String workspaceRoot;

    @Value("${daman.home:#{systemProperties['user.home']}/.daman}")
    private String damanHomePath;

    private Path workspace() { return Paths.get(workspaceRoot); }

    private Path damanHome() { return Paths.get(damanHomePath); }

    private Path backendResources() {
        return workspace().resolve("daman-backend/src/main/resources");
    }

    /** What the dev checkout is currently prepared as. All fields null when nothing is prepared. */
    public record DevCurrent(String clientCode, String mode, String version) {}

    // ── config / meta ────────────────────────────────────────────────────────

    /**
     * Prepares the checkout's {@code client.config.json} + {@code client-meta.properties}
     * for {@code clientCode} in the given {@code mode}:
     * <ul>
     *   <li>{@code per-client} — delegates to {@link ClientConfigService#prepareDevConfig(String)}
     *       (real exported config + {@code client.code=<code>} / {@code client.version=dev} meta,
     *       plus {@code ~/.daman/runtime.properties}).</li>
     *   <li>{@code generic} — copies the checked-in {@code client.config.generic.json} over
     *       {@code client.config.json}, writes a generic meta ({@code client.generic=true},
     *       {@code client.version=dev}), and writes {@code ~/.daman/runtime.properties} =
     *       {@code daman.runtime.client-code=<code>}.</li>
     * </ul>
     * Callers must validate the client first — {@link #devRun(String, DevRunRequest)} does.
     */
    public void prepareConfigForMode(String clientCode, String mode) {
        try {
            if ("per-client".equals(mode)) {
                clientConfigService.prepareDevConfig(clientCode); // config + meta + runtime.properties
            } else if ("generic".equals(mode)) {
                String genericJson = Files.readString(
                        workspace().resolve("daman-frontend/src/assets/client.config.generic.json"));
                String genericMeta = "# Auto-generated by DevRunService (dev-run, generic mode). Do not edit.\n"
                        + Files.readString(backendResources().resolve("client-meta.generic.properties")).trim()
                        + "\nclient.version=dev\nclient.builtAt=" + LocalDateTime.now() + "\n";
                clientConfigService.writeCheckoutConfig(genericJson, genericMeta);
                Files.createDirectories(damanHome());
                Files.writeString(damanHome().resolve("runtime.properties"),
                        "daman.runtime.client-code=" + clientCode + "\n");
            } else {
                throw new IllegalArgumentException("mode must be 'per-client' or 'generic'");
            }
        } catch (IOException e) {
            throw new UncheckedIOException("dev-run: failed writing config for mode " + mode, e);
        }
    }

    /**
     * Reads {@code client-meta.properties} (and, for generic mode, {@code ~/.daman/runtime.properties}
     * for the client code) to report what the checkout is currently prepared as.
     */
    public DevCurrent devCurrent() {
        Path meta = backendResources().resolve("client-meta.properties");
        if (!Files.exists(meta)) {
            return new DevCurrent(null, null, null);
        }
        try {
            Properties p = new Properties();
            try (var in = Files.newInputStream(meta)) {
                p.load(in);
            }
            String version = p.getProperty("client.version");
            if (!"dev".equals(version)) {
                // devReset() restored the neutral .generic meta (no client.version),
                // or this is a real packaged build's meta — nothing is "prepared" for
                // dev. Both prepareConfigForMode modes (generic here, per-client via
                // ClientConfigService.prepareDevConfig) write client.version=dev.
                return new DevCurrent(null, null, null);
            }
            if ("true".equalsIgnoreCase(p.getProperty("client.generic"))) {
                String code = null;
                Path rp = damanHome().resolve("runtime.properties");
                if (Files.exists(rp)) {
                    Properties rpp = new Properties();
                    try (var in = Files.newInputStream(rp)) {
                        rpp.load(in);
                    }
                    code = rpp.getProperty("daman.runtime.client-code");
                }
                return new DevCurrent(code, "generic", version);
            }
            String code = p.getProperty("client.code");
            return code == null
                    ? new DevCurrent(null, null, null)
                    : new DevCurrent(code, "per-client", version);
        } catch (IOException e) {
            log.warn("dev-current: could not read client-meta.properties", e);
            return new DevCurrent(null, null, null);
        }
    }

    /**
     * Restores the neutral generic config to the checkout and deletes
     * {@code ~/.daman/license.dat} + {@code ~/.daman/active-client.json}.
     * NEVER touches a database, a {@code ~/.daman/<code>/} data folder, or
     * {@code ~/.daman/runtime.properties}.
     */
    public void devReset() {
        try {
            String genericJson = Files.readString(
                    workspace().resolve("daman-frontend/src/assets/client.config.generic.json"));
            String genericMeta = Files.readString(
                    backendResources().resolve("client-meta.generic.properties"));
            clientConfigService.writeCheckoutConfig(genericJson, genericMeta);
            Files.deleteIfExists(damanHome().resolve("license.dat"));
            Files.deleteIfExists(damanHome().resolve("active-client.json"));
            // runtime.properties and every ~/.daman/<code>/ data folder are left untouched.
        } catch (IOException e) {
            throw new UncheckedIOException("dev-reset failed", e);
        }
    }

    // ── dev machine id / dev licence / db copy ───────────────────────────────

    /** {@code app_settings} key holding this dev machine's licence machine-ID. */
    public static final String DEV_MACHINE_ID_KEY = "dev_machine_id";

    /** The locally-running POS backend's status endpoint (desktop default port 8082). */
    private static final String LOCAL_STATUS_URL = "http://localhost:8082/api/license/status";

    /** Request for {@link #devRun(String, DevRunRequest)}. {@code dbFile} is nullable (no DB copy). */
    public record DevRunRequest(String mode, String dbFile) {}

    /** Outcome of a {@link #devRun(String, DevRunRequest)} call. */
    public record DevRunResult(String clientCode, String mode, String machineId,
                               String dbPath, boolean dbCopied, String licensePath, List<String> notes) {}

    /**
     * One call to "run the dev checkout as this client": validates the client,
     * prepares the checkout config for {@code mode} ({@code generic} when blank),
     * resolves this dev machine's licence machine-ID, mints — or <b>reuses</b> —
     * an ACTIVE dev v2 licence for {@code (machineId, clientCode)} (no 409 on a
     * repeat run), writes {@code ~/.daman/license.dat} + {@code ~/.daman/active-client.json},
     * and — when {@code req.dbFile()} is given — copies that database to
     * {@code ~/.daman/<code>/daman_db.sqlite}. Never deletes or truncates an
     * existing database or {@code ~/.daman/<code>/} folder.
     *
     * SECURITY: mints a licence with no machine-ID friction and writes the local
     * filesystem — acceptable ONLY because the admin backend is a locally-run
     * developer tool (see the class comment).
     */
    public DevRunResult devRun(String clientCode, DevRunRequest req) {
        String mode = (req.mode() == null || req.mode().isBlank()) ? "generic" : req.mode();
        var cfg = clientConfigRepository.findByClientCode(clientCode)
                .orElseThrow(() -> new IllegalArgumentException("Client not found: " + clientCode));

        prepareConfigForMode(clientCode, mode);

        String machineId = resolveDevMachineId();

        // Always regenerate from the client's CURRENT admin config and refresh the
        // dev-run licence row in place. Reusing a stored key verbatim meant any
        // later change to the client's features / base currency / brand colours /
        // app name stayed invisible until the licence was manually revoked — e.g.
        // a dev-run licence minted before v2 payloads carried `colors` never
        // delivered the client's primary/secondary, so a generic build fell back
        // to the neutral palette. Same row is reused (no 409, activatedAt/label
        // preserved); only the key + name are refreshed.
        var ent = clientConfigService.licenseEntitlementsFor(clientCode);
        String key = licenseKeyService.generateLicense(
                machineId, cfg.getAppName(), clientCode, null, ent.baseCurrency(), ent.features(),
                ent.colorPrimary(), ent.colorSecondary(), ent.adminUsername(), ent.adminPassword());
        License l = licenseRepository
                .findByMachineIdAndClientCodeAndStatus(machineId, clientCode, "ACTIVE")
                .orElseGet(() -> {
                    License n = new License();
                    n.setClientCode(clientCode);
                    n.setMachineId(machineId);
                    n.setStatus("ACTIVE");
                    n.setLabel("dev-run");
                    return n;
                });
        l.setLicenseKey(key);
        l.setClientName(cfg.getAppName());
        licenseRepository.save(l);

        Path home = damanHome();
        Path dbTarget = home.resolve(clientCode).resolve("daman_db.sqlite");
        boolean dbCopied = false;
        try {
            Files.createDirectories(home);
            Files.writeString(home.resolve("license.dat"), key);
            Files.writeString(home.resolve("active-client.json"), "{\"clientCode\":\"" + clientCode + "\"}");
            if (req.dbFile() != null && !req.dbFile().isBlank()) {
                Path src = Paths.get(req.dbFile());
                if (!Files.isRegularFile(src)) {
                    throw new IllegalArgumentException("dbFile not found: " + req.dbFile());
                }
                Files.createDirectories(dbTarget.getParent());
                // Atomic: stream to a sibling temp file, then swap it in with an
                // ATOMIC_MOVE. A mid-copy failure can no longer destroy the owner's
                // previously-imported daman_db.sqlite (REPLACE_EXISTING deletes the
                // target before it streams the first byte).
                Path tmp = dbTarget.resolveSibling("daman_db.sqlite.devrun-tmp");
                try {
                    Files.copy(src, tmp, StandardCopyOption.REPLACE_EXISTING);
                    Files.move(tmp, dbTarget, StandardCopyOption.REPLACE_EXISTING, StandardCopyOption.ATOMIC_MOVE);
                } finally {
                    Files.deleteIfExists(tmp);
                }
                dbCopied = true;
            }
        } catch (IOException e) {
            throw new UncheckedIOException("dev-run: failed writing licence / copying db", e);
        }

        syncInstallationIdentity(clientCode, cfg.getAppName(), cfg.getPhone());

        List<String> notes = new ArrayList<>();
        notes.add("Restart your local daman-backend (mvn spring-boot:run -Pdesktop, or your IntelliJ desktop run "
                + "config) and your ng serve — config, licence and DB are only read at startup.");
        if ("generic".equals(mode)) {
            notes.add("Generic mode: features + base currency come from the dev licence; in-app branding stays "
                    + "generic Daman (only receipts carry the client's logo).");
            notes.add("The packaged Electron generic build reads its own fixed data folder (~/.daman/data/), not "
                    + "this DB path — if that folder already existed from an earlier client, this dev-run only "
                    + "synced the store's name/phone into it, not its transactions/products. Provide dbFile if you "
                    + "need that data to match too.");
        }
        if (!dbCopied) {
            notes.add("Put the client's database at " + dbTarget + " before starting the backend.");
        }
        return new DevRunResult(clientCode, mode, machineId, dbTarget.toString(), dbCopied,
                home.resolve("license.dat").toString(), notes);
    }

    /**
     * Syncs {@code clientCode}'s real appName/phone into {@code installation_setup_settings}
     * on every local SQLite file a dev-run of this client might actually be read from — both
     * the per-client path a directly-run backend reads ({@code ~/.daman/<code>/}) and the
     * packaged generic build's fixed path ({@code ~/.daman/data/}), which never see the same
     * license.dat/database in the same way (see {@link #devRun} and the class comment).
     * Without this, switching which client you dev-run as left the PREVIOUSLY dev-run
     * client's store name/phone showing in the app — the license (a small file, always
     * freshly written) correctly said the new client, but the SQLite file's own business
     * data (entered once, long ago, via the app's first-run setup wizard) silently didn't
     * change. A no-op on any file that hasn't run its first boot yet (table doesn't exist).
     */
    private void syncInstallationIdentity(String clientCode, String appName, String phone) {
        List<Path> candidates = List.of(
                damanHome().resolve(clientCode).resolve("daman_db.sqlite"),
                damanHome().resolve("data").resolve("daman_db.sqlite"));
        for (Path dbPath : candidates) {
            if (!Files.isRegularFile(dbPath)) continue;
            String url = "jdbc:sqlite:" + dbPath.toAbsolutePath();
            try (Connection conn = DriverManager.getConnection(url)) {
                try (Statement check = conn.createStatement();
                     ResultSet rs = check.executeQuery(
                             "SELECT COUNT(*) FROM sqlite_master WHERE type='table' "
                                     + "AND name='installation_setup_settings'")) {
                    if (!rs.next() || rs.getInt(1) == 0) continue;
                }
                try (PreparedStatement ps = conn.prepareStatement(
                        "UPDATE installation_setup_settings SET app_name = ?, phone = ? WHERE id = 1")) {
                    ps.setString(1, appName);
                    ps.setString(2, phone);
                    int updated = ps.executeUpdate();
                    if (updated > 0) {
                        log.info("dev-run: synced installation identity for '{}' into {}", clientCode, dbPath);
                    }
                }
            } catch (SQLException e) {
                log.warn("dev-run: could not sync installation identity into {} — {}", dbPath, e.getMessage());
            }
        }
    }

    /**
     * This dev machine's licence machine-ID: the locally-running POS backend's
     * {@code /status} value when reachable (self-healing the stored copy when it
     * differs), else the last value stored in {@code app_settings}, else a hard
     * error telling the developer how to set it.
     */
    String resolveDevMachineId() {
        String probed = probeLocalMachineId().orElse(null);
        if (probed != null && !probed.isBlank()) {
            appSettingRepository.findBySettingKey(DEV_MACHINE_ID_KEY)
                    .filter(s -> !probed.equals(s.getValueJson()))
                    .ifPresent(s -> { s.setValueJson(probed); appSettingRepository.save(s); });
            if (appSettingRepository.findBySettingKey(DEV_MACHINE_ID_KEY).isEmpty()) {
                AppSetting s = new AppSetting();
                s.setSettingKey(DEV_MACHINE_ID_KEY);
                s.setValueJson(probed);
                appSettingRepository.save(s);
            }
            return probed;
        }
        return appSettingRepository.findBySettingKey(DEV_MACHINE_ID_KEY)
                .map(AppSetting::getValueJson)
                .filter(v -> v != null && !v.isBlank())
                .orElseThrow(() -> new IllegalStateException(
                        "Dev machine ID unknown — start your local daman-backend once, "
                        + "or PUT /api/clients/dev-machine-id with your machine ID."));
    }

    /**
     * GETs {@link #LOCAL_STATUS_URL} with a 1s connect + 1s request timeout and
     * returns its {@code machineId}. Empty on any failure (backend down, non-200,
     * unparseable body). Package-private so tests can stub it.
     */
    Optional<String> probeLocalMachineId() {
        try {
            HttpResponse<String> resp = HttpClient.newBuilder()
                    .connectTimeout(Duration.ofSeconds(1)).build()
                    .send(HttpRequest.newBuilder(URI.create(LOCAL_STATUS_URL))
                                    .timeout(Duration.ofSeconds(1)).GET().build(),
                            HttpResponse.BodyHandlers.ofString());
            if (resp.statusCode() != 200) return Optional.empty();
            JsonNode node = JsonMapper.builder().build().readTree(resp.body());
            String mid = node.path("machineId").asText("");
            return mid.isBlank() ? Optional.empty() : Optional.of(mid);
        } catch (Exception e) {
            return Optional.empty();
        }
    }

    /**
     * Manually sets this dev machine's licence machine-ID (upsert into
     * {@code app_settings}) — the escape hatch when the local POS backend can't be
     * started for the {@code /status} probe. Validates {@code ^[A-Za-z0-9]{16,128}$}.
     */
    public void setDevMachineId(String machineId) {
        if (machineId == null || !machineId.matches("^[A-Za-z0-9]{16,128}$")) {
            throw new IllegalArgumentException("machineId must be 16–128 hex/alphanumeric characters");
        }
        AppSetting s = appSettingRepository.findBySettingKey(DEV_MACHINE_ID_KEY).orElseGet(AppSetting::new);
        s.setSettingKey(DEV_MACHINE_ID_KEY);
        s.setValueJson(machineId);
        appSettingRepository.save(s);
    }
}
