package com.daman.admin.service;

import com.daman.admin.repository.AppSettingRepository;
import com.daman.admin.repository.ClientConfigRepository;
import com.daman.admin.repository.LicenseRepository;
import lombok.RequiredArgsConstructor;
import lombok.extern.slf4j.Slf4j;
import org.springframework.beans.factory.annotation.Value;
import org.springframework.stereotype.Service;

import java.io.IOException;
import java.io.UncheckedIOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.time.LocalDateTime;
import java.util.Properties;

/**
 * "Run the dev checkout as client X" — writes {@code client.config.json} /
 * {@code client-meta.properties} into the workspace (either the real per-client
 * config or the neutral generic one), drops {@code ~/.daman/runtime.properties},
 * and — in the machine-id / dev-licence / db-copy half added later — mints a dev
 * v2 licence and points the checkout at a database the owner chooses. {@link #devReset()}
 * puts the checkout back to the neutral generic config.
 *
 * SECURITY: every method here writes to the local filesystem and (in the licence
 * half) mints licences without the usual machine-ID friction. This is acceptable
 * ONLY because the admin backend is a locally-run developer tool. It must never be
 * reachable from a network-exposed admin backend — revisit before the
 * admin-Cloudflare-deploy work.
 */
@Service
@RequiredArgsConstructor
@Slf4j
public class DevRunService {

    // Injected for the dev-licence / machine-id / db-copy half of this service.
    private final ClientConfigService clientConfigService;
    private final LicenseKeyService licenseKeyService;
    private final LicenseRepository licenseRepository;
    private final ClientConfigRepository clientConfigRepository;
    private final AppSettingRepository appSettingRepository;

    @Value("${daman.workspace:D:/Daman/src}")
    private String workspaceRoot;

    @Value("${daman.home:#{systemProperties['user.home']}/.daman}")
    private String damanHomePath;

    private Path workspace() { return Paths.get(workspaceRoot); }

    private Path damanHome() { return Paths.get(damanHomePath); }

    private Path backendResources() {
        return workspace().resolve("daman-backend/src/main/resources");
    }

    /** What the dev checkout is currently prepared as. All fields null when nothing is prepared. */
    public record DevCurrent(String clientCode, String mode, String version) {}

    // ── config / meta ────────────────────────────────────────────────────────

    /**
     * Prepares the checkout's {@code client.config.json} + {@code client-meta.properties}
     * for {@code clientCode} in the given {@code mode}:
     * <ul>
     *   <li>{@code per-client} — delegates to {@link ClientConfigService#prepareDevConfig(String)}
     *       (real exported config + {@code client.code=<code>} / {@code client.version=dev} meta,
     *       plus {@code ~/.daman/runtime.properties}).</li>
     *   <li>{@code generic} — copies the checked-in {@code client.config.generic.json} over
     *       {@code client.config.json}, writes a generic meta ({@code client.generic=true},
     *       {@code client.version=dev}), and writes {@code ~/.daman/runtime.properties} =
     *       {@code daman.runtime.client-code=<code>}.</li>
     * </ul>
     */
    public void prepareConfigForMode(String clientCode, String mode) {
        try {
            if ("per-client".equals(mode)) {
                clientConfigService.prepareDevConfig(clientCode); // config + meta + runtime.properties
            } else if ("generic".equals(mode)) {
                String genericJson = Files.readString(
                        workspace().resolve("daman-frontend/src/assets/client.config.generic.json"));
                String genericMeta = "# Auto-generated by DevRunService (dev-run, generic mode). Do not edit.\n"
                        + Files.readString(backendResources().resolve("client-meta.generic.properties")).trim()
                        + "\nclient.version=dev\nclient.builtAt=" + LocalDateTime.now() + "\n";
                clientConfigService.writeCheckoutConfig(genericJson, genericMeta);
                Files.createDirectories(damanHome());
                Files.writeString(damanHome().resolve("runtime.properties"),
                        "daman.runtime.client-code=" + clientCode + "\n");
            } else {
                throw new IllegalArgumentException("mode must be 'per-client' or 'generic'");
            }
        } catch (IOException e) {
            throw new UncheckedIOException("dev-run: failed writing config for mode " + mode, e);
        }
    }

    /**
     * Reads {@code client-meta.properties} (and, for generic mode, {@code ~/.daman/runtime.properties}
     * for the client code) to report what the checkout is currently prepared as.
     */
    public DevCurrent devCurrent() {
        Path meta = backendResources().resolve("client-meta.properties");
        if (!Files.exists(meta)) {
            return new DevCurrent(null, null, null);
        }
        try {
            Properties p = new Properties();
            try (var in = Files.newInputStream(meta)) {
                p.load(in);
            }
            String version = p.getProperty("client.version");
            if ("true".equalsIgnoreCase(p.getProperty("client.generic"))) {
                String code = null;
                Path rp = damanHome().resolve("runtime.properties");
                if (Files.exists(rp)) {
                    Properties rpp = new Properties();
                    try (var in = Files.newInputStream(rp)) {
                        rpp.load(in);
                    }
                    code = rpp.getProperty("daman.runtime.client-code");
                }
                return new DevCurrent(code, "generic", version);
            }
            String code = p.getProperty("client.code");
            return code == null
                    ? new DevCurrent(null, null, null)
                    : new DevCurrent(code, "per-client", version);
        } catch (IOException e) {
            log.warn("dev-current: could not read client-meta.properties", e);
            return new DevCurrent(null, null, null);
        }
    }

    /**
     * Restores the neutral generic config to the checkout and deletes
     * {@code ~/.daman/license.dat} + {@code ~/.daman/active-client.json}.
     * NEVER touches a database, a {@code ~/.daman/<code>/} data folder, or
     * {@code ~/.daman/runtime.properties}.
     */
    public void devReset() {
        try {
            String genericJson = Files.readString(
                    workspace().resolve("daman-frontend/src/assets/client.config.generic.json"));
            String genericMeta = Files.readString(
                    backendResources().resolve("client-meta.generic.properties"));
            clientConfigService.writeCheckoutConfig(genericJson, genericMeta);
            Files.deleteIfExists(damanHome().resolve("license.dat"));
            Files.deleteIfExists(damanHome().resolve("active-client.json"));
            // runtime.properties and every ~/.daman/<code>/ data folder are left untouched.
        } catch (IOException e) {
            throw new UncheckedIOException("dev-reset failed", e);
        }
    }
}
